sudo: required
services:
    - docker

before_install:
    - docker build -t bijaymaharjan/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true bijaymaharjan/react-test npm run test -- --coverage

after_success:
    - docker build -t bijaymaharjan/multi-client ./client
    - docker build -t bijaymaharjan/multi-nginx ./nginx
    - docker build -t bijaymaharjan/multi-server ./server
    - docker build -t bijaymaharjan/multi-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push bijaymaharjan/multi-client
    - docker push bijaymaharjan/multi-nginx
    - docker push bijaymaharjan/multi-server
    - docker push bijaymaharjan/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-1-524741345639
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: "$AWS_SECRET_KEY"